version: '2.1'  
services:  
  plexmediaserver:
    build: .
    image: awesomecontainer/wdocker-plexmediaserver:${DOCKERTAG:-latest}
    container_name: plexmediaserver
    volumes:
      - C:\DockerData\plexmediaserver:c:\PlexData
    network_mode: nat
    restart: unless-stopped
    ports:
      - 32400:32400
      - 32400:32400/udp
      - 32469:32469
      - 32469:32469/udp
      - 1900:1900/udp
    environment:
      - PLEX_MEDIA_SERVER_INFO_DEVICE=docker
    stdin_open: true